on: [push]
name: Setup Haskell
jobs:
  runhaskell:
    name: Haskell Project
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.7.6
        with:
          ghc-version: '9.4.8' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: runhaskell test/*.hs
